### ISSUE TITLE
Rename Autoprefixer Included

### ISSUE THREAD

**Issue by ai** [MicheleBertoli/css-in-js#20]
Most of projects doesn't contain Autoprefixer itself, but v use some other tool.

Maybe we should write column name more clear, like "Vendor Prefixes"?

**Comment by MicheleBertoli** [comment]
You are right, @ai 

To be honest, when I named the column "Autoprefixer Included" I wasn't referring to any particular implementations but I see your point.

What about "Automatic Vendor Prefixing"?

**Comment by ai** [comment]
Sounds good :-)
