### ISSUE TITLE
proposal - include in the table one more column 'server side render'

### ISSUE THREAD

**Issue by b2whats** [MicheleBertoli/css-in-js#33]
split it into 2 parts - opportunity server side render and get critical css from server code

**Comment by b2whats** [comment]
also may be add another column - available selectors (> + ~ X[attr])

**Comment by stereobooster** [comment]
We will be able to add more columns as soon as we will implement website. New version of website https://github.com/MicheleBertoli/css-in-js/pull/58.

**Comment by MicheleBertoli** [comment]
I'm closing this in favor of #73
