### ISSUE TITLE
jss autoprefixer

### ISSUE THREAD

**Issue by kof** [MicheleBertoli/css-in-js#4]
its actually included, using plugin https://github.com/jsstyles/jss-vendor-prefixer

**Comment by MicheleBertoli** [comment]
Thanks @kof! 
I saw the plugin but I didn't find a way to install it using [react-jss](https://github.com/jsstyles/react-jss).

**Comment by kof** [comment]
you mean how to setup it?

**Comment by kof** [comment]
or how to install it through npm

**Comment by MicheleBertoli** [comment]
Since I don't have access to `jss` I can't call `jss.use`, right?

**Comment by kof** [comment]
haha of course you have an access ... never thought its an issue do udnerstand .. react-jss is just a convenience function for jss, its using jss ... you can just require('jss') and do everything ...

Do you think its a common missunderstanding and worth noting in the documentation?

**Comment by MicheleBertoli** [comment]
Now it's clear, thanks!
Maybe a little paragraph in the readme could help :)

**Comment by kof** [comment]
looks great, thanks, added a note to react-jss

**Comment by kof** [comment]
Also I am going to add css export via jss-cli so that I can fill all your checkboxes )))

**Comment by MicheleBertoli** [comment]
Amazing :)

**Comment by MicheleBertoli** [comment]
Amazing!
