### ISSUE TITLE
Add Uranium -- universal media queries in React Native and React

### ISSUE THREAD

**Issue by tuckerconnelly** [MicheleBertoli/css-in-js#40]
Just released this guy :) https://github.com/tuckerconnelly/uranium

Benefit is that it works in both React Native and React, and works with server-side rendering

**Comment by MicheleBertoli** [comment]
Hello @tuckerconnelly,
I'm trying to create an example with Uranium but I've got some problems.

If I install the following deps:
```json
"react": "15.3.2",
"react-dom": "15.3.2",
"react-native-web": "0.0.53",
"uranium": "github:tuckerconnelly/uranium"
```

I get this errors at build time:
```bash
ERROR in ./~/uranium/lib/plugins/copyStyles.js
Module not found: Error: Cannot resolve module 'react-native-universal' in /css-in-js/uranium/node_modules/uranium/lib/plugins
 @ ./~/uranium/lib/plugins/copyStyles.js 2:26-59

ERROR in ./~/uranium/lib/plugins/mediaQueries.js
Module not found: Error: Cannot resolve module 'react-native-universal' in /css-in-js/uranium/node_modules/uranium/lib/plugins
 @ ./~/uranium/lib/plugins/mediaQueries.js 2:26-59
```

If I then install `react-native-universal`:
```json
"react-native-universal": "0.0.2",
```

I get this error at build time:
```bash
ERROR in ./~/react-native-universal/index.js
Module not found: Error: Cannot resolve module 'react-native' in /css-in-js/uranium/node_modules/react-native-universal
 @ ./~/react-native-universal/index.js 2:22-45
```

If I then install `react-native`:
```json
"react-native": "0.37.0",
```

I get multiples errors like this at build time:
```
ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ActivityIndicator' in /css-in-js/uranium/node_modules/react-native/Libraries/react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 30:35-63
```

The bundle at this point works, but all the styles applied with my custom classes are overwritten by the default styles applied inline.
Can you please take a look at the [uranium](https://github.com/MicheleBertoli/css-in-js/tree/uranium) branch?

**Comment by tuckerconnelly** [comment]
Hey dude, I removed the peer dependency on react-native-universal. If you pull down the latest, it should just work :)
