### ISSUE TITLE
Blog post on measuring performances between CSS-in-JS libraries on the server.

### ISSUE THREAD

**Issue by PepijnSenders** [MicheleBertoli/css-in-js#46]
Hey @MicheleBertoli, I wrote a blog post on the repo I saw you already starred. Maybe something for the testimonials? 😄 

Post: https://engineering.hellofresh.com/the-css-in-js-battle-89c34a7a83ea#.igooociw6
Repo: github.com/hellofresh/css-in-js-perf-tests

**Comment by MicheleBertoli** [comment]
Hello @PepijnSenders, I've seen your blog post on Twitter and it's great.
However, I usually add to the "Testimonial" section only talks, posts or tweets that mention this repo.

**Comment by PepijnSenders** [comment]
Makes sense @MicheleBertoli, maybe an idea to add a news section 😉 ?

**Comment by MicheleBertoli** [comment]
That's a very good point @PepijnSenders.
Some months ago, @rofrischmann and I were talking about creating a website for the repo and use it as a central hub for blog posts, talks, etc. about CSSinJS.

**Comment by PepijnSenders** [comment]
Yeah I definitely think the community is screaming for some good resources, there are so many out there!
