### ISSUE TITLE
`last update` column in css-in-js table

### ISSUE THREAD

**Issue by serapath** [MicheleBertoli/css-in-js#48]
Currently, projects are sorted alphabetically.
It would be really nice to instead have them sorted by `last update`

Maybe there are services/bots that could be set to update that table on `major` or maybe even `minor` version updates... not sure... but i'm coming back to `css-in-js` in irregular intervals to check if there is a new cool project :-)

Maybe there are already easy ways to figure out what to check, but i don't find it trivial to see what changed.

**Comment by MicheleBertoli** [comment]
Hello @serapath, thanks for opening the issue.

I understand your point, and I believe it makes a lot of sense.
When you come back to the repo, it's not easy to figure out which packages have been updated and see if new libraries have been added to the list.

What you can do at the moment is checking the commits but is suboptimal.
Let me leave this open and think about a solution.

**Comment by derhuerst** [comment]
@serapath Maybe you can subscribe to this as an RSS feed: https://github.com/MicheleBertoli/css-in-js/commits/master/README.md.

**Comment by MicheleBertoli** [comment]
I'm closing this in favor of #73
