### ISSUE TITLE
Column request: Uses CSS syntax

### ISSUE THREAD

**Issue by gertsonderby** [MicheleBertoli/css-in-js#49]
At least some of the listed libraries use CSS syntax, rather than or as well as object literals (`styled-components`, `styled-jsx`, etc.), some only permit objects. It would be nice if this was also part of the table, since that is a significant factor for those who for example have to port existing CSS, or use third-party components that do not style themselves.

**Comment by MicheleBertoli** [comment]
I'm closing this in favor of #73
