### ISSUE TITLE
Use `x` to represent `support`, there will be some ambiguity.

### ISSUE THREAD

**Issue by blade254353074** [MicheleBertoli/css-in-js#57]
May be `✔️`/`√` or `✅`?

**Comment by MicheleBertoli** [comment]
Thanks @blade254353074.
This is the first time I heard the 'x' on the table is ambiguous.
Let's leave this open and see if someone else has the same opinion.

**Comment by blade254353074** [comment]
OK~
This probably a language habit.
When we first saw this form, my friend and I thought 'x' was not support. 😂
We are Chinese.

**Comment by Dafrok** [comment]
***X*** marks indicates ***wrong***, ***no***, ***not***, ***error*** in such a lot of countries. Both I and my friend @blade254353074 thought ***x*** means not support at first.

> [Wiki - X mark](https://en.wikipedia.org/wiki/X_mark)

**Comment by Dafrok** [comment]
***X*** marks indicates ***wrong***, ***no***, ***not***, ***off***, ***error*** and so on in such a lot of countries. Both I and my friend @blade254353074 thought ***x*** means not support at first.

> [Wikipedia - X mark](https://en.wikipedia.org/wiki/X_mark)
> An x mark (also known as a cross, x, ex, exmark or into mark[1]) is a mark (x, ×, X, ✕, ☓, ✖, ✗, ✘, etc.) used to indicate the concept of negation (for example "no, this has not been verified" or "no, I don't agree") as well as an indicator (for example in election ballot papers or in x marks the spot). Its opposite is often considered to be the check mark or tick (or the O mark used in Japan, Korea and Taiwan). In Japanese, the X mark (×) is called "batsu" (ばつ) and can be expressed by someone by crossing their arms.
> In some areas it's common for people to check a square box with a cross rather than a check mark, while in others the check mark (✓) or even a v mark[citation needed] is used.

**Comment by MicheleBertoli** [comment]
That's interesting, thanks @Dafrok.
I agree X means "negation" in some cases, but it depends on the context.

For example:

> [...] as well as an indicator (for example in election ballot papers or in x marks the spot).

> In some areas it's common for people to check a square box with a cross rather than a check mark [...]

That said, a PR replacing X with ✓ will be accepted :)

**Comment by MicheleBertoli** [comment]
🙌 Thanks!
