### ISSUE TITLE
Should "jss" and "j2c" be included?

### ISSUE THREAD

**Issue by serapath** [MicheleBertoli/css-in-js#6]
[jss](https://github.com/jsstyles/jss)
[j2c](https://github.com/pygy/j2c)

**Comment by MicheleBertoli** [comment]
hey @serapath thanks for your suggestion!
jss is already included (see [react-jss](https://github.com/MicheleBertoli/css-in-js/tree/master/react-jss)), I'll add j2c soon.
PRs are welcome too :)
