### ISSUE TITLE
Request for adding stars in the data sheet

### ISSUE THREAD

**Issue by vaidsu** [MicheleBertoli/css-in-js#60]
# Feature request

This is a great effort, more like a booklet of awesome frameworks. 

I was trying add the GitHub stars per project in the last column, but for some reason I wasn't able to do it. Most badges require some JS script to be embedded, I even tried the shields.io badges, but wasn't successful. 

If this is in your charter, may I help putting this together? Unless we head to github pages, or a separate website, anyway doing this? 

Thanks.

**Comment by MicheleBertoli** [comment]
Hello @vaidsu, thanks for opening this issue.
Adding the number of stars would be a cool idea, I'm not sure how it works but it seems you already tried and you didn't manage to.
Also, there's was a project around building a website for the repo, let's see what happens!

**Comment by vaidsu** [comment]
> I'm not sure how it works

Thanks @MicheleBertoli for quick response. I saw a PR and you responded about another parallel effort. Let me check for PRs and see to contribute to it. 

Other naive method, worked is to use a script and make that nightly, which automatically updates the dependencies and stars in the table and auto raises PR. 

Also do we need to  commission awesome_bot on the ``column-1`` links to ensure the validity? Sometimes users move the repos and it shows 404. Not that I see an example in your links, but just asking for info. 

Thanks again.

**Comment by MicheleBertoli** [comment]
Creating a script that runs overnight to update the number of stars seems a bit too much for this purpose, let's see if there's an easier way.

Checking for 404s would be useful, sometimes happened that the URL of a repo was changed.

Thanks!

**Comment by stereobooster** [comment]
As of 404 https://github.com/stevenvachon/broken-link-checker

**Comment by vaidsu** [comment]
@MicheleBertoli  Thanks for your comment. Sorry for delay 
@stereobooster 
I have tried this before: https://github.com/dkhamsing/awesome_bot

**Comment by JNaftali** [comment]
https://github.com/ddavison/github-badges
For example here's the badge for this repo - ![css-in-js](http://githubbadges.com/star.svg?user=MicheleBertoli&repo=css-in-js&background=28a745&color=fff&style=flat "css-in-js")

**Comment by stereobooster** [comment]
@JNaftali yeah I tried it here https://gist.github.com/stereobooster/13a26188d4ad5382bc6da9ffe76ce3e1#file-1-react-google-maps-md

It is super annoying when there are a lot of them and they all slowly loading. So I discourage this approach

**Comment by MicheleBertoli** [comment]
I'm closing this in favor of #73
