### ISSUE TITLE
Add i-css

### ISSUE THREAD

**Issue by irom-io** [MicheleBertoli/css-in-js#62]
Please, add my new package for using css in js.
https://github.com/irom-io/i-css

**Comment by MicheleBertoli** [comment]
Hello @irom-io, thanks for your package.
I guess you are the best person to add the package to the repo.
Do you mind opening a PR? Thanks!

**Comment by irom-io** [comment]
Hello, i created a PR: https://github.com/MicheleBertoli/css-in-js/pull/63

**Comment by MicheleBertoli** [comment]
This is awesme, thanks @irom-io.
