### ISSUE TITLE
Avoid globals

### ISSUE THREAD

**Issue by caub** [MicheleBertoli/css-in-js#82]
https://github.com/MicheleBertoli/css-in-js/blob/bfdc913e8263874e0426568921989e7c61ee1f6c/babel-plugin-css-in-js/button.js#L4

it's a global? @martinandert

**Comment by streamich** [comment]
It looks like that.

**Comment by stereobooster** [comment]
Is https://github.com/martinandert/babel-plugin-css-in-js/issues more appropriate for this issue?

**Comment by caub** [comment]
yes @stereobooster right
