### ISSUE TITLE
I would like to include some more features

### ISSUE THREAD

**Issue by kof** [MicheleBertoli/css-in-js#9]
- @keyframes support
- @font-face support
- extensibility/plugins api
- fallbacks
- framework agnostic (not just react)
- rendering technics: 
  - generates CSS and inserts style element
  - uses inline styles
  - mixed mode: inline styles, CSS, reacts event system for :hover and co (radium)

Also I would add below a description for each feature.

**Comment by MicheleBertoli** [comment]
hey @kof,

adding some columns and descriptions would help.
For example, it would be nice to know if a package supports the server-side rendering or not.

In general, I would prefer to keep the table as minimalistic as possible listing just the "key" features.
In my opinion, the most important thing are the code examples for each package.

For people who wants a massive list of features the [Radium's one](https://github.com/FormidableLabs/radium/tree/master/docs/comparison) is perfect.

**Comment by kof** [comment]
Well, how do you know what a key feature is and what not) it depends on use case. I thought the intent is to compare those components from all possible aspects.

**Comment by MicheleBertoli** [comment]
You are right, @kof 
I just think that if the columns are too much, the table becomes less useful ;)

**Comment by kof** [comment]
Yes, we need a better format.

**Comment by HighOnDrive** [comment]
There should also be a column for solutions that work outside of React, like the exceptional JSStyles API. Being bound to only one framework is automatically not that great.

**Comment by MicheleBertoli** [comment]
We would need an interactive page, like: http://reactcheatsheet.com/

**Comment by rtsao** [comment]
@HighOnDrive agreed on having another column that indicates whether React is a dependency or not.

@MicheleBertoli I would be interested in helping create the interactive page (presumably to be hosted on gh-pages). 

It would be nice to have a comprehensive table/repo that isn't https://github.com/FormidableLabs/radium/tree/master/docs/comparison which IMHO is biased with unhelpful platitudes such as "same pitfalls as CSS"

**Comment by MicheleBertoli** [comment]
That would be awesome @rtsao.
I'm going to make you a collaborator, ok?

**Comment by rofrischmann** [comment]
If there's something I can help you with, just text me :) I'd love to have a rich and dynamic comparison page. @MicheleBertoli

**Comment by MicheleBertoli** [comment]
Sounds great @rofrischmann.

I'll be more than happy to create a web app all together.
Are you still in @rtsao?

@kof's feature are very important, we just need something better than a table to show them.

**Comment by rtsao** [comment]
@MicheleBertoli Yes, I'm down!

**Comment by MicheleBertoli** [comment]
Here we go @rofrischmann @rtsao 

[![Gitter](https://badges.gitter.im/MicheleBertoli/css-in-js.svg)](https://gitter.im/MicheleBertoli/css-in-js?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

**Comment by rofrischmann** [comment]
Short update @kof @MicheleBertoli I have started drafting a simple interactive, responsive listing. I will push a first version soon :P

**Comment by MicheleBertoli** [comment]
awesome @rofrischmann, thanks!
can't wait to see it :)

**Comment by rofrischmann** [comment]
We should perhaps also shoutout to all the owners to add additional information soon. ;)

**Comment by tomByrer** [comment]
I hope to see it soon; about to build a new tech stack from scratch, so the extra info will help.

**Comment by kof** [comment]
added "rendering technics" to the description

**Comment by rofrischmann** [comment]
I was kind of busy lately, will push the page by the end of the week hopefully.

**Comment by MoOx** [comment]
Having a column to say if a lib is compatible with react native would be nice (eg: react-look does via react-look-native).

**Comment by Kielan** [comment]
@rofrischmann if you have any progress feel free to push it in a separate repo and someone can maybe help you out. 

Is there no list of reserved keys for this project available to developers? I am looking for the equivalent to transition-delay I assumed it would be transitionDelay: '0.2s',

**Comment by rofrischmann** [comment]
Finally pushed first table implementation. One can sort (ASC/DESC) by clicking column headers, search by package names and filter requirements. Still we need to improve the UX/UI as it basically is ugly right now, but it works.
Also I will add a mobile-friendly version soon, but first I guess we now need all the data for all the packages.

**Comment by buildbreakdo** [comment]
Some pretty big items missing from this like: 

- Are CSS rule declaration bodies safe by default? React Inline runs everything through escapeTextContentForBrowser to avoid XSS.
- Are at-media selectors safe by default (@import is open to XSS)?
- Is there a build step?
- Unique syntax?
- Selectors scoped or still in global namespace?

**Comment by rofrischmann** [comment]
I guess we can merge the first 2 and just call it XSS vulnerability? The others seem to be fine. I may add those later on :) Thank you @buildbreakdo

**Comment by stereobooster** [comment]
How about push existing version + every undefined value mark in table as grey area e.g. unknown. After working version will be online it will be fastly populated by volunteers

**Comment by stereobooster** [comment]
New version of website https://github.com/MicheleBertoli/css-in-js/pull/58

**Comment by stereobooster** [comment]
I want to add more columns to https://stereobooster.github.io/css-in-js/ and I thought it would be nice actually define what each feature mean, illustrate it with example, show advantages disadvantages of each approach. So I started this repo https://github.com/stereobooster/css-in-js-systematic-approach/

**Comment by MicheleBertoli** [comment]
🎉 http://michelebertoli.github.io/css-in-js/ 🎉
Thanks @stereobooster

**Comment by stereobooster** [comment]
Almost finished polishing of "CSS-in-JS 101"

![css-in-js](https://user-images.githubusercontent.com/179534/33519264-f86f9f66-d7a3-11e7-8c03-853f4b1907da.png)

As soon as we agree on terminology. I want to start to add more features (columns to table).

**Comment by MicheleBertoli** [comment]
I'm closing this in favor of #73
