### ISSUE TITLE
Format numbers in README

### ISSUE THREAD

**Issue by MicheleBertoli** [MicheleBertoli/css-in-js#94]
We recently added more data to the README, such as GitHub stars and monthly downloads for each package.
However, we are not formatting the numbers and this makes the information hard to read.

![untitled 2](https://user-images.githubusercontent.com/1308971/41497520-c529114c-714e-11e8-9bd6-e9970db9bcc1.png)

This is for first-contributors only - feel free to ping me if you need help.

**Comment by karanjthakkar** [comment]
IIUC, would this require adding a number formatter on [this line](https://github.com/MicheleBertoli/css-in-js/blob/master/ReadmeSrc/Rows.js#L77)?
